<?php

return [
    [
        'class' => 'yii\rest\UrlRule',
        'controller' => [
            'api/empresa',
            'api/login',
            'api/jurisdicciones',
            'api/juzgados',
            'api/multimedia',
            'api/nominaciones',
            'api/estados-caso',
            'api/objetivos',
            'api/roles-tipo-caso',
            'api/tipos-movimiento',
            'api/notificaciones',
            'api/clientes',
            'api/ciudades',
            'api/gmail',
            'api/report',
            'api/competencias',
            'api/estado-ambito-gestion',
            'api/webhook'
        ],
        'pluralize' => false
    ],
    [
        'class' => 'yii\rest\UrlRule',
        'controller' => ['api/usuarios'],
        'pluralize' => false,
        'patterns' => [
            'POST cambiar-password' => 'cambiar-password',
            'POST existe' => 'existe',
            'POST validar-codigo' => 'validar-codigo',
            'POST' => 'create',
            'POST recuperar-cuenta' => 'recuperar-cuenta',
            'POST set-token-app' => 'set-token-app',
            'POST set-token-app-cliente' => 'set-token-app-cliente',
            'POST alta-cliente' => 'alta-cliente',
            'POST reporte-cliente' => 'reporte-cliente',
            'PUT,PATCH' => 'update',
            'DELETE {id}' => 'delete',
            'GET,HEAD {id}/listar-permisos' => 'listar-permisos',
            'GET,HEAD {id}' => 'view',
            'GET,HEAD' => 'index',
            '{id}' => 'options',
            '' => 'options',
            'alta-cliente' => 'options',
            'reporte-cliente' => 'options',
            'recuperar-cuenta' => 'options',
            'set-token-app-cliente' => 'options',
            'set-token-app' => 'options',
            'existe' => 'options',
        ],
    ],
    [
        'class' => 'yii\rest\UrlRule',
        'controller' => ['api/personas'],
        'pluralize' => false,
        'patterns' => [
            'POST {id}/alta-telefono' => 'alta-telefono',
            'POST {id}/modificar' => 'update',
            'POST {id}/eliminar-telefono' => 'eliminar',
            'POST {id}/editar-documentacion' => 'editar-documentacion',
            'POST parametros' => 'parametros',
            'POST historia-clinica' => 'historia-clinica',
            'GET casos' => 'personas-casos',
            'GET padron' => 'padron',
            '{id}/alta-telefono' => 'options',
            '{id}/modificar' => 'options',
            '{id}/eliminar-telefono' => 'options',
            '{id}/editar-documentacion' => 'options',
            'casos' => 'options',
            'parametros' => 'options',
            'historia-clinica' => 'options',
        ],
    ],
    [
        'class' => 'yii\rest\UrlRule',
        'controller' => ['api/estudios'],
        'pluralize' => false,
        'tokens' => [
            '{id}' => '<id:\\w+>',
            '{idPersona}'=>'<idPersona:\\w+>'
        ],
        'patterns' => [
            'PUT,PATCH {id}/modificar-persona/{idPersona}' => 'modificar-persona',
            'PUT,PATCH' => 'update',
            'DELETE {id}' => 'delete',
            'GET,HEAD {id}/estados-caso' => 'estados-caso',
            'GET,HEAD {id}/buscar-personas' => 'buscar-personas',
            'GET,HEAD {id}/mensajes-estudio' => 'mensajes-estudio',
            'GET,HEAD {id}/origenes' => 'origenes',
            'GET,HEAD {id}/tipos-movimiento' => 'tipos-movimiento',
            'GET,HEAD {id}/intervalo-fechas-movimientos' => 'intervalo-fechas-movimientos',
            'GET,HEAD {id}/usuarios' => 'usuarios',
            'GET,HEAD {id}/calendario' => 'calendario',
            'GET,HEAD {id}/cuadernos' => 'cuadernos',
            'GET,HEAD listar' => 'listar',
            'GET,HEAD listar-documentacion-solicitada' => 'listar-documentacion-solicitada',
            'GET,HEAD eventos' => 'eventos',
            'GET,HEAD {id}' => 'view',
            'GET,HEAD' => 'index',
            'POST alta-documentacion-solicitada' => 'alta-documentacion-solicitada',
            '{id}/modificar-persona/{idPersona}' => 'options',
            '{id}/intervalo-fechas-movimientos' => 'options',
            '{id}/estados-caso' => 'options',
            '{id}/buscar-personas' => 'options',
            '{id}/mensajes-estudio' => 'options',
            '{id}/origenes' => 'options',
            '{id}/tipos-movimiento' => 'options',
            '{id}/usuarios' => 'usuarios',
            '{id}/calendario' => 'options',
            '{id}/cuadernos' => 'options',
            '/listar' => 'options',
            '/listar-documentacion-solicitada' => 'options',
            'eventos' => 'options',
            'alta-documentacion-solicitada' => 'options',
            '{id}' => 'options',
            '' => 'options',
        ],
    ],
    [
        'class' => 'yii\rest\UrlRule',
        'controller' => ['api/tipos-caso'],
        'pluralize' => false,
        'patterns' => [
            'GET,HEAD {id}/roles' => 'roles',
            'GET,HEAD {id}/juzgados' => 'juzgados',
            'GET,HEAD {id}' => 'view',
            'GET,HEAD' => 'index',
            '{id}/roles' => 'options',
            '{id}/juzgados' => 'options',
            '{id}/' => 'options',
            '{id}' => 'options',
            '' => 'options',
        ],
    ],
    [
        'class' => 'yii\rest\UrlRule',
        'controller' => ['api/casos'],
        'tokens' => [
            '{id}' => '<id:\\w+>',
            '{idPersona}'=>'<idPersona:\\w+>'
        ],
        'pluralize' => false,
        'patterns' => [
            'POST' => 'create',
            'POST wordpress' => 'wordpress-create',
            'POST usuarios' => 'usuarios',
            'POST compartir' => 'compartir',
            'POST compartir-por-estudio/{id}' => 'compartir-por-estudio',
            'POST eliminar-comparticion/{id}' => 'eliminar-comparticion',
            'POST eliminar-usuario' => 'eliminar-usuario',
            'POST causa-penal' => 'causa-penal',
            'POST finalizar-casos' => 'finalizar-casos',
            'POST alta-carpeta' => 'alta-carpeta',
            'POST editar-carpeta' => 'editar-carpeta',
            'POST borrar-carpeta' => 'borrar-carpeta',
            'POST duplicar-caso' => 'duplicar-caso',
            'POST alta-etiqueta' => 'alta-etiqueta',
            'POST borrar-etiqueta' => 'borrar-etiqueta',
            'POST guardar-combo' => 'guardar-combo',
            'POST alta-combo' => 'alta-combo',
            'POST parametros' => 'parametros',
            'POST {id}/alta-persona' => 'alta-persona',
            'POST {id}/borrar-persona/{idPersona}' => 'borrar-persona',
            'POST editar-opciones-parametros' => 'editar-opciones-parametros',
            'POST alta-contacto-parametros' => 'alta-contacto-parametros',
            'PUT {id}/archivar' => 'archivar',
            'PUT {id}/baja' => 'baja',
            'PUT,PATCH {id}' => 'update',
            'DELETE {id}' => 'delete',
            'GET {id}/personas' => 'personas',
            'GET {id}/persona/{idPersona}' => 'persona',
            'GET {id}/movimientos' => 'movimientos',
            'GET {id}/movimientos-clientes' => 'movimientos-clientes',
            'GET {id}/movimientos-sin-realizar' => 'movimientos-sin-realizar',
            'GET {id}/movimientos-realizados' => 'movimientos-realizados',
            'GET {id}/previsualizar-borrado' => 'previsualizar-borrado',
            'GET compartidos' => 'compartidos',
            'GET buscar' => 'buscar',
            'GET test' => 'test',
            'GET buscar-judiciales' => 'buscar-judiciales',
            'GET buscar-cliente' => 'buscar-cliente',
            'GET eventos-clientes' => 'eventos-clientes',
            'GET listar-carpetas' => 'listar-carpetas',
            'GET listar-etiquetas' => 'listar-etiquetas',
            'GET opciones-parametros' => 'opciones-parametros',
            'GET buscar-contacto-parametros' => 'buscar-contacto-parametros',
            'GET,HEAD {id}' => 'view',
            'GET,HEAD' => 'index',
            'GET numero-casos' => 'numero-casos',
            '{id}/personas' => 'options',
            '{id}/persona/{idPersona}' => 'options',
            '{id}/movimientos' => 'options',
            '{id}/movimientos-clientes' => 'options',
            '{id}/movimientos-sin-realizar' => 'options',
            '{id}/movimientos-realizados' => 'options',
            '{id}/previsualizar-borrado' => 'options',
            '{id}/archivar' => 'options',
            '{id}/baja' => 'options',
            '{id}' => 'options',
            '' => 'options',
            'buscar' => 'options',
            'test' => 'options',
            'buscar-cliente' => 'options',
            'buscar-judiciales' => 'options',
            'eventos-clientes' => 'options',
            'alta-carpeta' => 'options',
            'editar-carpeta' => 'options',
            'borrar-carpeta' => 'options',
            'listar-carpetas' => 'options',
            'guardar-combo' => 'options',
            'duplicar-caso' => 'options',
            'alta-combo' => 'options',
            'alta-etiqueta' => 'options',
            'finalizar-casos' => 'options',
            'borrar-etiqueta' => 'options',
            'listar-etiquetas' => 'options',
            'wordpress' => 'options',
            'numero-casos' => 'options',
            'parametros' => 'options',
            'causa-penal' => 'options',
            'opciones-parametros' => 'options',
            'buscar-contacto-parametros' => 'buscar-contacto-parametros',
            'alta-contacto-parametros' => 'buscar-contacto-parametros',
            'editar-opciones-parametros' => 'options',
            'compartir-por-estudio/{id}' => 'options',
            'eliminar-comparticion/{id}' => 'options',
            '{id}/borrar-persona/{idPersona}' => 'options',
            '{id}/alta-persona' => 'options'
        ],
    ],
    [
        'class' => 'yii\rest\UrlRule',
        'controller' => ['api/origenes'],
        'pluralize' => false,
        'patterns' => [
            'GET,HEAD {id}' => 'view',
            'GET,HEAD' => 'index',
            '{id}' => 'options',
            '' => 'options'
        ]
    ],
    [
        'class' => 'yii\rest\UrlRule',
        'controller' => ['api/consultas'],
        'pluralize' => false,
        'patterns' => [
            'POST' => 'create',
            'PUT,PATCH {id}/aceptar-derivacion' => 'aceptar-derivacion',
            'PUT,PATCH {id}/rechazar-derivacion' => 'rechazar-derivacion',
            'GET,HEAD {id}' => 'view',
            'GET,HEAD' => 'index',
            '{id}/aceptar-derivacion' => 'options',
            '{id}/rechazar-derivacion' => 'options',
            '{id}' => 'options',
            '' => 'options',
        ],
    ],
    [
        'class' => 'yii\rest\UrlRule',
        'controller' => ['api/movimientos'],
        'pluralize' => false,
        'tokens' => [
            '{id}' => '<id:\\w+>',
            '{idObjetivo}'=>'<idObjetivo:\\w+>'
        ],
        'patterns' => [
            'POST {id}/asociar-objetivo/{idObjetivo}' => 'asociar-objetivo',
            'POST' => 'create',
            'PUT,PATCH {id}/desasociar-objetivo/{idObjetivo}' => 'desasociar-objetivo',
            'PUT,PATCH {id}/realizar' => 'realizar',
            'PUT,PATCH {id}/desrealizar' => 'desrealizar',
            'PUT,PATCH {id}' => 'update',
            'POST alta-recordatorio' => 'alta-recordatorio',
            'DELETE {id}' => 'delete',
            'GET,HEAD vista-tribunales' => 'vista-tribunales',
            'POST eventos' => 'crear-evento',
            'GET,HEAD movimientos-del-dia' => 'movimientos-home',
            'GET,HEAD {id}' => 'view',
            '{id}/asociar-objetivo/{idObjetivo}' => 'options',
            '{id}/desasociar-objetivo/{idObjetivo}' => 'options',
            '{id}/realizar' => 'options',
            '{id}/desrealizar' => 'options',
            '{id}' => 'options',
            'vista-tribunales' => 'options',
            'eventos' => 'options',
            'alta-recordatorio' => 'options',
            'movimientos-del-dia' => 'options',
            '' => 'options',
        ],
    ],
    [
        'class' => 'yii\rest\UrlRule',
        'controller' => ['api/chats'],
        'pluralize' => false,
        'patterns' => [
            'POST crear' => 'create',
            'GET,HEAD {id}' => 'view',
            'POST {id}/actualizar' => 'update',
            'POST {id}/actualizar-telefono' => 'update-telefono',
            'POST reemplazar-caso' => 'reemplazar-caso',
            'DELETE {telefono}' => 'delete',
            'crear' => 'options',
            '{id}' => 'options',
            '{id}/actualizar' => 'options',
            '{id}/actualizar-telefono' => 'options',
            'reemplazar-caso' => 'options'
        ]
    ],
    [
        'class' => 'yii\rest\UrlRule',
        'controller' => ['api/mensajes'],
        'pluralize' => false,
        'patterns' => [
            'POST enviar'  => 'enviar-mensaje',
            'POST enviar-template'  => 'enviar-template',
            'POST enviar-externo'  => 'enviar-mensaje-externo',
            'POST enviar-template-externo'  => 'enviar-mensaje-externo',
            'POST mensaje-global'  => 'mensaje-global',
            'POST mensaje-template-global'  => 'mensaje-global-template',
            'POST mensaje-comun'  => 'mensaje-comun',
            'GET,HEAD {id}' => 'listar-mensajes',
            'GET,HEAD listar-mensajes-externo' => 'listar-mensajes-externo',
            'GET,HEAD chats-externo' => 'chats-externo',
            'GET,HEAD nuevos-mensajes' => 'nuevos-mensajes',
            'GET,HEAD nuevos-mensajes-externo' => 'nuevos-mensajes-externo',
            'chats-externo' => 'options',
            'enviar' => 'options',
            'enviar-template' => 'options',
            'enviar-template-externo' => 'options',
            'enviar-externo' => 'options',
            'mensaje-global' => 'options',
            'mensaje-global-template' => 'options',
            'mensaje-comun' => 'options',
            '{id}' => 'options',
            'listar-mensajes-externo' => 'options',
            'nuevos-mensajes' => 'options',
            'nuevos-mensajes-externo' => 'options'
        ]
    ],
    [
        'class' => 'yii\rest\UrlRule',
        'controller' => ['api/mensajes-interno'],
        'pluralize' => false,
        'patterns' => [
            'POST enviar'  => 'enviar-mensaje',
            'POST update'  => 'update-mensajes',
            'GET,HEAD' => 'listar-mensajes',
            'GET,HEAD nuevos-mensajes' => 'nuevos-mensajes',
            'enviar' => 'options',
            'update' => 'options',
            '' => 'options',
            'nuevos-mensajes' => 'options'
        ]
    ],
    [
        'class' => 'yii\rest\UrlRule',
        'controller' => ['api/test'],
        'pluralize' => false,
        'patterns' => [
            'GET,HEAD' => 'index',
            'GET,HEAD test' => 'test',
            'POST update' => 'update',
            '' => 'options',
            'update' => 'options',
            'test' => 'options'
        ]
    ],
    [
        'class' => 'yii\rest\UrlRule',
        'controller' => ['api/comentarios-caso'],
        'pluralize' => false,
        'patterns' => [
            'GET,HEAD' => 'index',
            'GET,HEAD comentarios-sin-leer' => 'comentarios-sin-leer',
            'POST alta' => 'alta',
            'POST comentario-visto' => 'comentario-visto',
            '' => 'options',
            'alta' => 'options',
            'comentario-visto' => 'options',
            'comentarios-sin-leer' => 'options'
        ]
    ],
    [
        'class' => 'yii\rest\UrlRule',
        'controller' => ['api/multimedia-caso'],
        'pluralize' => false,
        'patterns' => [
            'GET,HEAD' => 'index',
            'POST alta' => 'alta',
            'POST eliminar' => 'eliminar',
            'POST enviar-email' => 'enviar-email',
            'POST editar-nombre' => 'editar-nombre',
            'POST documento' => 'documento',
            'POST mover' => 'mover',
            'POST masivo' => 'masivo',
            'GET,HEAD descarga-multiple' => 'descarga-multiple',
            'GET,HEAD generar-pdf' => 'generar-pdf',
            '' => 'options',
            'alta' => 'options',
            'eliminar' => 'options',
            'enviar-email' => 'options',
            'documento' => 'options',
            'mover' => 'options',
            'descarga-multiple' => 'options',
            'generar-pdf' => 'options',
            'masivo' => 'options'
        ]
    ],
    [
        'class' => 'yii\rest\UrlRule',
        'controller' => ['api/plantillas'],
        'pluralize' => false,
        'patterns' => [
            'GET,HEAD' => 'index',
            'POST alta' => 'alta',
            'POST alta-carpeta' => 'alta-carpeta',
            'POST eliminar' => 'eliminar',
            'POST eliminar-carpeta' => 'eliminar-carpeta',
            'POST editar' => 'editar',
            'POST editar-carpeta' => 'editar-carpeta',
            'POST mover-elementos' => 'mover-elementos',
            '' => 'options',
            'alta' => 'options',
            'alta-carpeta' => 'options',
            'eliminar' => 'options',
            'eliminar-carpeta' => 'options',
            'editar' => 'options',
            'editar-carpeta' => 'options',
            'mover-elementos' => 'options'
        ]
    ],
    [
        'class' => 'yii\rest\UrlRule',
        'controller' => ['api/casos-pendientes'],
        'pluralize' => false,
        'patterns' => [
            'GET,HEAD' => 'index',
            'GET,HEAD buscar-caso' => 'buscar-caso',
            'GET,HEAD estados' => 'estados',
            'GET,HEAD similitudes' => 'similitudes',
            'POST alta' => 'alta',
            'POST alta-caso-activo' => 'alta-caso-activo',
            'POST activar-caso' => 'activar-caso',
            'POST eliminar' => 'eliminar',
            'POST editar' => 'editar',
            '' => 'options',
            'buscar-caso' => 'options',
            'estados' => 'options',
            'similitudes' => 'options',
            'alta' => 'options',
            'alta-caso-activo' => 'options',
            'activar-caso' => 'options',
            'eliminar' => 'options',
            'editar' => 'options'
        ]
    ],
    [
        'class' => 'yii\rest\UrlRule',
        'controller' => ['api/mediaciones'],
        'pluralize' => false,
        'patterns' => [
            'GET,HEAD' => 'index',
            'GET,HEAD datos' => 'datos',
            'GET,HEAD mediadores' => 'mediadores',
            'GET,HEAD buscar' => 'buscar',
            'GET,HEAD fechas' => 'fechas',
            'POST alta' => 'alta',
            'POST editar' => 'editar',
            'POST evento' => 'evento',
            '' => 'options',
            'datos' => 'options',
            'mediadores' => 'options',
            'buscar' => 'options',
            'fechas' => 'options',
            'alta' => 'options',
            'editar' => 'options',
            'evento' => 'options'
        ]
    ],
    [
        'class' => 'yii\rest\UrlRule',
        'controller' => ['api/mediadores'],
        'pluralize' => false,
        'patterns' => [
            'GET,HEAD' => 'index',
            'GET,HEAD contar-mediadores' => 'contar-mediadores',
            'POST editar-contacto' => 'editar-contacto',
            'POST alta-contacto' => 'alta-contacto',
            '' => 'options',
            'contar-mediadores' => 'options',
            'editar-contacto' => 'options',
            'alta-contacto' => 'options'
        ]
    ],
    [
        'class' => 'yii\rest\UrlRule',
        'controller' => ['api/contactos'],
        'pluralize' => false,
        'patterns' => [
            'GET,HEAD' => 'index',
            'POST editar-contacto' => 'editar-contacto',
            'POST alta-contacto' => 'alta-contacto',
            'POST alta-multimedia' => 'alta-multimedia',
            'POST borrar-contacto' => 'borrar-contacto',
            'GET,HEAD buscar-contacto' => 'buscar-contacto',
            'GET,HEAD contar-contacto' => 'buscar-contacto',
            '' => 'options',
            'editar-contacto' => 'options',
            'alta-contacto' => 'options',
            'alta-multimedia' => 'options',
            'buscar-contacto' => 'options',
            'contar-contacto' => 'options',
            'borrar-contacto' => 'options'
        ]
    ],
    [
        'class' => 'yii\rest\UrlRule',
        'controller' => ['api/eventos'],
        'pluralize' => false,
        'patterns' => [
            'POST' => 'create',
            '' => 'options'
        ]
    ]
];
