CREATE TABLE `CasosPendientes` (
  `IdCasoPendiente` int(11) NOT NULL AUTO_INCREMENT,
  `Apellidos` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `Nombres` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `Domicilio` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `Telefono` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `Prioridad` char(1) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `IdEstadoCasoPendiente` int(11) NOT NULL,
  `IdOrigen` int(11) NOT NULL,
  `Documento` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
  `Visitado` char(1) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `Latitud` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `Longitud` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `IdEstudio` int(11) NOT NULL,
  `FechaAlta` datetime NOT NULL,
  `Lesion` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `IdCaso` bigint(20) NOT NULL,
  `IdPersona` int(11) NOT NULL,
  `FechaEstado` datetime DEFAULT NULL,
  `FechaVisitado` date DEFAULT NULL,
  `IdUsuarioVisita` int(11) DEFAULT NULL,
  PRIMARY KEY (`IdCasoPendiente`),
  KEY `fk_CasosPendientes_1_idx` (`IdOrigen`),
  KEY `fk_CasosPendientes_2_idx` (`IdEstadoCasoPendiente`),
  KEY `fk_CasosPendientes_3_idx` (`IdEstudio`),
  KEY `fk_CasosPendientes_4_idx` (`IdCaso`),
  KEY `fk_CasosPendientes_5_idx` (`IdPersona`),
  KEY `fk_CasosPendientes_4_idx1` (`IdUsuarioVisita`),
  CONSTRAINT `fk_CasosPendientes_1` FOREIGN KEY (`IdOrigen`) REFERENCES `Origenes` (`IdOrigen`),
  CONSTRAINT `fk_CasosPendientes_2` FOREIGN KEY (`IdEstadoCasoPendiente`) REFERENCES `EstadosCasoPendiente` (`IdEstadoCasoPendiente`),
  CONSTRAINT `fk_CasosPendientes_3` FOREIGN KEY (`IdEstudio`) REFERENCES `Estudios` (`IdEstudio`),
  CONSTRAINT `fk_CasosPendientes_4` FOREIGN KEY (`IdUsuarioVisita`) REFERENCES `Usuarios` (`IdUsuario`)
) ENGINE=InnoDB AUTO_INCREMENT=816 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
