CREATE TABLE `Casos` (
  `IdCaso` bigint(20) NOT NULL,
  `IdJuzgado` int(11) DEFAULT NULL,
  `IdNominacion` int(11) DEFAULT NULL,
  `IdCompetencia` int(11) NOT NULL DEFAULT '1',
  `IdTipoCaso` smallint(6) NOT NULL,
  `IdEstadoCaso` int(11) DEFAULT NULL,
  `IdEstadoAmbitoGestion` int(11) DEFAULT NULL,
  `IdOrigen` int(11) DEFAULT NULL,
  `Caratula` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `NroExpediente` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `FechaEstado` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Carpeta` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `FechaAlta` datetime NOT NULL,
  `Observaciones` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `FechaUltVisita` datetime DEFAULT NULL,
  `Estado` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`IdCaso`),
  KEY `RefOrigenes68` (`IdOrigen`),
  KEY `RefNominaciones23` (`IdNominacion`),
  KEY `RefEstadosCaso35` (`IdEstadoCaso`),
  KEY `RefJuzgadosXX1_idx` (`IdJuzgado`),
  KEY `fk_Casos_1_idx` (`IdCompetencia`,`IdTipoCaso`),
  CONSTRAINT `RefEstadosCaso35` FOREIGN KEY (`IdEstadoCaso`) REFERENCES `EstadosCaso` (`IdEstadoCaso`),
  CONSTRAINT `RefNominaciones23` FOREIGN KEY (`IdNominacion`) REFERENCES `Nominaciones` (`IdNominacion`),
  CONSTRAINT `RefOrigenes68` FOREIGN KEY (`IdOrigen`) REFERENCES `Origenes` (`IdOrigen`),
  CONSTRAINT `fk_Casos_1` FOREIGN KEY (`IdCompetencia`, `IdTipoCaso`) REFERENCES `CompetenciasTiposCaso` (`IdCompetencia`, `IdTipoCaso`),
  CONSTRAINT `fk_Casos_Juzgados` FOREIGN KEY (`IdJuzgado`) REFERENCES `Juzgados` (`IdJuzgado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
