CREATE TABLE `Casos` (
  `IdCaso` bigint NOT NULL,
  `IdJuzgado` int DEFAULT NULL,
  `IdNominacion` int DEFAULT NULL,
  `IdCompetencia` int NOT NULL DEFAULT '1',
  `IdTipoCaso` smallint NOT NULL,
  `IdEstadoCaso` int DEFAULT NULL,
  `IdEstadoAmbitoGestion` int DEFAULT NULL,
  `IdOrigen` int DEFAULT NULL,
  `Caratula` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `NroExpediente` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `FechaEstado` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Carpeta` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `FechaAlta` datetime NOT NULL,
  `Observaciones` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `FechaUltVisita` datetime DEFAULT NULL,
  `Estado` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `Defiende` char(1) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`IdCaso`),
  KEY `RefOrigenes68` (`IdOrigen`),
  KEY `RefNominaciones23` (`IdNominacion`),
  KEY `RefEstadosCaso35` (`IdEstadoCaso`),
  KEY `RefJuzgadosXX1_idx` (`IdJuzgado`),
  KEY `fk_Casos_1_idx` (`IdCompetencia`,`IdTipoCaso`),
  KEY `index7` (`FechaAlta` DESC),
  KEY `index8` (`Caratula`),
  CONSTRAINT `fk_Casos_1` FOREIGN KEY (`IdCompetencia`, `IdTipoCaso`) REFERENCES `CompetenciasTiposCaso` (`IdCompetencia`, `IdTipoCaso`),
  CONSTRAINT `fk_Casos_Juzgados` FOREIGN KEY (`IdJuzgado`) REFERENCES `Juzgados` (`IdJuzgado`),
  CONSTRAINT `RefEstadosCaso35` FOREIGN KEY (`IdEstadoCaso`) REFERENCES `EstadosCaso` (`IdEstadoCaso`),
  CONSTRAINT `RefNominaciones23` FOREIGN KEY (`IdNominacion`) REFERENCES `Nominaciones` (`IdNominacion`),
  CONSTRAINT `RefOrigenes68` FOREIGN KEY (`IdOrigen`) REFERENCES `Origenes` (`IdOrigen`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
