CREATE TABLE `MovimientosCaso` (
  `IdMovimientoCaso` bigint(20) NOT NULL AUTO_INCREMENT,
  `IdCaso` bigint(20) NOT NULL,
  `IdTipoMov` int(11) NOT NULL,
  `IdUsuarioCaso` int(11) NOT NULL,
  `IdResponsable` int(11) DEFAULT NULL,
  `Detalle` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `FechaAlta` datetime NOT NULL,
  `FechaEdicion` datetime DEFAULT NULL,
  `FechaEsperada` datetime DEFAULT NULL,
  `FechaRealizado` datetime DEFAULT NULL,
  `Cuaderno` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `Escrito` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `Color` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`IdMovimientoCaso`,`IdCaso`),
  UNIQUE KEY `UI_IdMovimientoCaso` (`IdMovimientoCaso`),
  KEY `RefCasos31` (`IdCaso`),
  KEY `RefTiposMovimiento32` (`IdTipoMov`),
  KEY `RefUsuariosCaso73` (`IdUsuarioCaso`),
  KEY `RefUsuariosCaso74` (`IdResponsable`),
  CONSTRAINT `RefCasos31` FOREIGN KEY (`IdCaso`) REFERENCES `Casos` (`IdCaso`),
  CONSTRAINT `RefUsuariosCaso73` FOREIGN KEY (`IdUsuarioCaso`) REFERENCES `UsuariosCaso` (`IdUsuarioCaso`),
  CONSTRAINT `RefUsuariosCaso74` FOREIGN KEY (`IdResponsable`) REFERENCES `UsuariosCaso` (`IdUsuarioCaso`),
  CONSTRAINT `fk_MovimientosCaso_1` FOREIGN KEY (`IdTipoMov`) REFERENCES `TiposMovimiento` (`IdTipoMov`)
) ENGINE=InnoDB AUTO_INCREMENT=4671 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
